---
title: "Enrichment Graphs/Pie Graphs"
author: "Michayla Moore"
date: "2023-01-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE, echo=FALSE, results = 'hide', message = FALSE}
#if(!"rWikiPathways" %in% installed.packages()){
 #   if (!requireNamespace("BiocManager", quietly = TRUE))
  #      install.packages("BiocManager")
   # BiocManager::install("rWikiPathways", update = FALSE)
#}
library(rWikiPathways)
library(DOSE)
library(org.Hs.eg.db)
library(GO.db)
library(clusterProfiler)
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)
library(RColorBrewer)
library(RCy3)

#install.packages('pcr')
#devtools::install_github('MahShaaban/pcr')
#devtools::install_github('cttobin/ggthemr')
library(pcr)
library(ggplot2)
library(tidyverse)

# add t-test results to graph
# install.packages("ggpubr")
library(ggpubr)
library(dplyr)

# update ggplot theme 
theme_update(plot.title = element_text(hjust = 0.5))
library(ggeasy) 
#load and save pictures
library(extrafont)
#font_import(prompt = FALSE, pattern = "calibri")
#fonts()
loadfonts(device = "win")
library(dplyr)
library(tidyverse)
library(patchwork)

library(tidyverse)
library(stringr)
library(gt)
```

```{r}
#GO Enrichment
#load data and view 
lung.expr <- read.csv(("hHiPCtoEC_Data_Enrichment.csv"),stringsAsFactors = FALSE)
head(lung.expr)
```

```{r, warning = FALSE, echo=FALSE}
# Filter unregulated (> 1.1), downregulated ( < 0.7), (,1 takes ID's from column 1)
up.genes <- lung.expr[lung.expr$log2FC > 0.2 & lung.expr$adj.P.Value < 0.05, 1] 
dn.genes <- lung.expr[lung.expr$log2FC < -0.2 & lung.expr$adj.P.Value < 0.05, 1]
bkgd.genes <- lung.expr[,1]

# switch ID's to entrez ID (bitr is the converter) 
# keytypes(org.Hs.eg.db)
up.genes.entrez <- clusterProfiler::bitr(up.genes,fromType = "ACCNUM",toType = "ENTREZID",OrgDb = org.Hs.eg.db)
dn.genes.entrez <- bitr(dn.genes,fromType = "ACCNUM",toType = "ENTREZID",OrgDb = org.Hs.eg.db)
bkgd.genes.entrez <- bitr(bkgd.genes,fromType = "ACCNUM",toType = "ENTREZID",OrgDb = org.Hs.eg.db)
```

```{r}
# BIOLOGICAL PROCESS ONLY
# website of code https://rdrr.io/bioc/rWikiPathways/f/vignettes/Pathway-Analysis.Rmd
# Upregulated only BP
egobp <- clusterProfiler::enrichGO(
        gene     = up.genes.entrez[[2]],
        universe = bkgd.genes.entrez[[2]],
        OrgDb    = org.Hs.eg.db,
        ont      = "BP",
        pAdjustMethod = "fdr",
        pvalueCutoff = 0.05, 
        readable = TRUE)

# Make results a data frame and save to CSV
BP_enrichment_results_upreg <- as.data.frame(egobp)
BP_enrichment_results_upreg
write.csv(BP_enrichment_results_upreg, "C:/Users/MMoore2.MEHEALTH/Desktop/Paper_2023/GO_enrichment_results_upreg.csv", row.names = TRUE)

# Select cardiovascular specific enrichment terms
cardio <- BP_enrichment_results_upreg[c("GO:0001568", "GO:0001944", "GO:0072359", "GO:0048514", "GO:0042127", "GO:0008283", "GO:0061045", "GO:0045765", "GO:1901342", "GO:0001525", "GO:1901343", "GO:2000181", "GO:1901343"),]
  
# Plot 1:20 all terms
go_terms_all_upreg <- ggplot(egobp[1:20], aes(x=reorder(Description, -pvalue), y=Count, fill=-p.adjust)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    scale_fill_continuous(low="#b3b3b3", high="blue") +
    labs(x = "", y = "", fill = "p.adjust") +
    theme(axis.text=element_text(size=11),
          colour = "black") +
    theme_minimal() +
    ggtitle(label = "GO Functional Analysis of Secretome",
            subtitle = "Biological Process") +
    ylab("Hit Proteins") +
    theme(axis.text.y=element_text(colour = "black")) 
  
# Plot cardio terms
go_terms_cardio_upreg <- ggplot(cardio, aes(x=reorder(Description, -pvalue), y=Count, fill=-p.adjust)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    scale_fill_continuous(low="#b3b3b3", high="black") +
    labs(x = "", y = "", fill = "p.adjust") +
    theme(axis.text=element_text(size=11),
          colour = "black") +
    theme_minimal() +
    ggtitle("Prioritized Cardiovascular Terms",
            subtitle = "Biological Process") +
    ylab("Hit Proteins") +
    theme(axis.text.y=element_text(colour = "black")) 

go_terms_all_upreg
go_terms_cardio_upreg

# save to png
#ggsave("go_terms_all_upreg.png", device = "png", 
 #      width = 16, height = 8, units = "cm", 
  #     dpi = 600)

#ggsave("go_terms_cardio_upreg.png", device = "png", 
 #      width = 16, height = 8, units = "cm", 
  #     dpi = 600)
```

```{r}
go_terms_cardio_upreg <- ggplot(cardio, aes(x=reorder(Description, -pvalue), y=Count, fill=-p.adjust)) +
  geom_bar(stat = "identity") +
  coord_flip() +  # Flip coordinates to make horizontal bar plot
  scale_fill_continuous(low="#b3b3b3", high="blue") +
  labs(x = "", y = "", fill = "p.adjust") +
  theme_minimal() +  # Use minimal theme
  theme(
    axis.text = element_text(size = 11, colour = "black"),  # Size and color for axis text
    axis.title.y = element_text(size = 12, colour = "black"),  # Y-axis title size and color
    axis.title.x = element_text(size = 12, colour = "black"),  # X-axis title size and color
    legend.position = "left",  # Move the legend to the left
    plot.title = element_text(size = 14, face = "bold"),  # Title styling
    plot.subtitle = element_text(size = 12)  # Subtitle styling
  ) +
  ggtitle("Prioritized Cardiovascular Terms",
          subtitle = "Biological Process") +
  ylab("Hit Proteins")  # Y-axis label (will be on the right side in a flipped plot)

# Print the plot
print(go_terms_cardio_upreg)
```


```{r}
# BIOLOGICAL PROCESS ONLY
#Down-regulated only BP
egobp2 <- clusterProfiler::enrichGO(
        gene     = dn.genes.entrez[[2]],
        universe = bkgd.genes.entrez[[2]],
        OrgDb    = org.Hs.eg.db,
        ont      = "BP",
        pAdjustMethod = "fdr",
        pvalueCutoff = 0.05, 
        readable = TRUE)

BP_enrichment_results_downreg <- as.data.frame(egobp2)
BP_enrichment_results_downreg

cardio2 <- BP_enrichment_results_downreg[c("GO:0001568", "GO:0001944", "GO:0072359", "GO:0048514", "GO:0042127", "GO:0008283", "GO:0061045", "GO:0045765", "GO:1901342", "GO:0001525", "GO:1901343", "GO:2000181", "GO:1901343"),]

go_terms_all_downreg <- ggplot(egobp2[1:20], aes(x=reorder(Description, -pvalue), y=Count, fill=-p.adjust)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    scale_fill_continuous(low="#b3b3b3", high="#c1272d") +
    labs(x = "", y = "", fill = "p.adjust") +
    theme(axis.text=element_text(size=11),
          colour = "black") +
    theme_minimal() +
    ggtitle("Down-Regulated Proteins") +
    ylab("Count") +
    theme(axis.text.y=element_text(colour = "black")) 
  

go_terms_cardio_downreg <- ggplot(cardio2, aes(x=reorder(Description, -pvalue), y=Count, fill=-p.adjust)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    scale_fill_continuous(low="#b3b3b3", high="#c1272d") +
    labs(x = "", y = "", fill = "p.adjust") +
    theme(axis.text=element_text(size=11),
          colour = "black") +
    theme_minimal() +
    ggtitle("Prioritized Cardiovascular Terms (Down-Regulated)") +
    ylab("Count")

go_terms_all_downreg
go_terms_cardio_downreg
```

```{r}
# CELLULAR COMPONENT ONLY
#Upregulated only CC
egobp3 <- clusterProfiler::enrichGO(
        gene     = up.genes.entrez[[2]],
        universe = bkgd.genes.entrez[[2]],
        OrgDb    = org.Hs.eg.db,
        ont      = "CC",
        pAdjustMethod = "fdr",
        pvalueCutoff = 0.05, 
        readable = TRUE)

# SAVE
CC_enrichment_results_upreg <- as.data.frame(egobp3)
CC_enrichment_results_upreg
write.csv(CC_enrichment_results_upreg, "C:/Users/MMoore2.MEHEALTH/Desktop/Paper_2023/GO_enrichment_results_upreg.csv", row.names = TRUE)

egobp33 <- as.data.frame(egobp3)

CC_terms_all_upreg <- ggplot(egobp3[1:15], aes(x=reorder(Description, -pvalue), y=Count, fill=-p.adjust)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    scale_fill_continuous(low="#b3b3b3", high="black") +
    labs(x = "", y = "", fill = "p.adjust") +
    theme(axis.text=element_text(size=11),
          colour = "black") +
    theme_minimal() +
    ggtitle(label = "hHiPC to EC (Upregulated)",
            subtitle = "Cellular Component") +
    ylab("Hit Proteins") 
  
CC_terms_all_upreg

#Downregulated only CC
egobp3dn <- clusterProfiler::enrichGO(
        gene     = dn.genes.entrez[[2]],
        universe = bkgd.genes.entrez[[2]],
        OrgDb    = org.Hs.eg.db,
        ont      = "CC",
        pAdjustMethod = "fdr",
        pvalueCutoff = 0.05, 
        readable = TRUE)

# SAVE
CC_enrichment_results_dnreg <- as.data.frame(egobp3dn)
CC_enrichment_results_dnreg
write.csv(CC_enrichment_results_dnreg, "C:/Users/MMoore2.MEHEALTH/Desktop/Paper_2023/GO_enrichment_results_dnreg.csv", row.names = TRUE)

egobp33dn <- as.data.frame(egobp3dn)

CC_terms_all_dnreg <- ggplot(egobp3dn[1:14], aes(x=reorder(Description, -pvalue), y=Count, fill=-p.adjust)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    scale_fill_continuous(low="#b3b3b3", high="#c1272d") +
    labs(x = "", y = "", fill = "p.adjust") +
    theme(axis.text=element_text(size=11),
          colour = "black") +
    theme_minimal() +
    ggtitle(label = "hHiPC to EC (Downregulated)",
            subtitle = "Cellular Component") +
    ylab("Hit Proteins") 
  
CC_terms_all_dnreg

ggsave("CC_terms_all_upreg.png", device = "png", 
       width = 16, height = 8, units = "cm", 
       dpi = 600)
```


```{r}
# MOLECULAR FUNCTION ONLY
#Upregulated only MF
egobp4 <- clusterProfiler::enrichGO(
        gene     = up.genes.entrez[[2]],
        universe = bkgd.genes.entrez[[2]],
        OrgDb    = org.Hs.eg.db,
        ont      = "MF",
        pAdjustMethod = "fdr",
        pvalueCutoff = 0.05, 
        readable = TRUE)

MF_enrichment_results_upreg <- as.data.frame(egobp4)
MF_enrichment_results_upreg

MF_terms_all_upreg <- ggplot(egobp4[1:9], aes(x=reorder(Description, -pvalue), y=Count, fill=-p.adjust)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    scale_fill_continuous(low="#b3b3b3", high="blue") +
    labs(x = "", y = "", fill = "p.adjust") +
    theme(axis.text=element_text(size=11),
          colour = "black") +
    theme_minimal() +
    ggtitle(label = "MF Upregulated",
            subtitle = "Molecular Function") +
    ylab("Hit Proteins") 

#Downregulated only MF
egobp4dn <- clusterProfiler::enrichGO(
        gene     = dn.genes.entrez[[2]],
        universe = bkgd.genes.entrez[[2]],
        OrgDb    = org.Hs.eg.db,
        ont      = "MF",
        pAdjustMethod = "fdr",
        pvalueCutoff = 0.05, 
        readable = TRUE)

MF_enrichment_results_dnreg <- as.data.frame(egobp4dn)
MF_enrichment_results_dnreg

MF_terms_all_dnreg <- ggplot(egobp4dn[1:3], aes(x=reorder(Description, -pvalue), y=Count, fill=-p.adjust)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    scale_fill_continuous(low="#b3b3b3", high="#c1272d") +
    labs(x = "", y = "", fill = "p.adjust") +
    theme(axis.text=element_text(size=11),
          colour = "black") +
    theme_minimal() +
    ggtitle(label = "MF Downregulated",
            subtitle = "Molecular Function") +
    ylab("Hit Proteins")


MF_terms_all_upreg
MF_terms_all_dnreg
```


```{r}
# Pie Charts for Paper TAKEN FROM BAC DATA SET
data <- read.csv("CM_Percent_PieChart.csv")

os = data %>% group_by(Secreted) %>% 
  count() %>% 
  ungroup() %>% 
  filter(Secreted != "NA") %>% 
  mutate(percentage = n/sum(n)*100) %>%
  mutate_if(is.numeric, round, digits = 0) %>%
  mutate(label = paste(Secreted,"\n","(", percentage, "% ",")", sep = ""))

os$Secreted[os$Secreted == 'NonSignalPeptide'] <- 'Non Signal Peptide'
os$Secreted[os$Secreted == 'SignalPeptide'] <- 'Signal Peptide'
os <- os[,-4]

pie1 <- ggpubr::ggdonutchart(os, "percentage", label = "Secreted",
                     color = "white",fill = "Secreted",
                     palette = c("hotpink", "lightblue2")) +
  geom_text(aes(label = scales::percent(percentage/sum(percentage))),
            position = position_stack(vjust = 0.5),
            color = "white") + 
  labs(fill = "") +
  theme_void() +
  scale_fill_manual(values = c("Non Signal Peptide" = "#b3b3b3", "Signal Peptide" = "#c1272d")) 

piechart_CM <- pie1  

piechart_CM + ggtitle("Conditioned Media") +
  theme(plot.title = element_text(hjust = 0.5))

ggsave("piechart_CM.png", device = "png", 
       width = 16, height = 8, units = "cm", 
       dpi = 600)

#AA4499 CC6677
```

```{r}
#Cell lysate pie chart
data2 <- read.csv("Lysate_Percent_PieChart.csv")

os2 = data2 %>% group_by(Secreted) %>% 
  count() %>% 
  ungroup() %>% 
  filter(Secreted != "NA") %>% 
  mutate(percentage = n/sum(n)*100) %>%
  mutate_if(is.numeric, round, digits = 0) %>%
  mutate(label = paste(Secreted,"\n","(", percentage, "% ",")", sep = ""))

os2$Secreted[os2$Secreted == 'NonSignalPeptide'] <- 'Non Signal Peptide'
os2$Secreted[os2$Secreted == 'SignalPeptide'] <- 'Signal Peptide'
os2 <- os2[,-4]

pie2 <- ggpubr::ggdonutchart(os2, "percentage", label = "Secreted",
                     color = "white",fill = "Secreted",
                     palette = c("hotpink", "lightblue2")) +
  geom_text(aes(label = scales::percent(percentage/sum(percentage))),
            position = position_stack(vjust = 0.5),
            color = "white") + 
  labs(fill = "") +
  theme_void() +
  scale_fill_manual(values = c("Non Signal Peptide" = "#b3b3b3", "Signal Peptide" = "#c1272d")) 

piechart_LYSATE <- pie2

piechart_LYSATE + ggtitle("Cell Lysate") +
  theme(plot.title = element_text(hjust = 0.5))

ggsave("piechart_LYSATE.png", device = "png", 
       width = 16, height = 8, units = "cm", 
       dpi = 600) 
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
#Barb Data CM BMP9

#Import Data
#Make sure data is in tidy format and save as ".csv".
SWATH_results <- read_csv("BMP9_to_ControlBAC.csv")
as.tibble(SWATH_results)

#Change column names
colnames(SWATH_results)[3] = "Peak_Name"
colnames(SWATH_results)[5] = "Ret_Time"
colnames(SWATH_results)[9] = "P_Value"
colnames(SWATH_results)[17] = "Fold_Change"
colnames(SWATH_results)[18] = "Log_Fold_Change"
colnames(SWATH_results)[20] = "GO_Biological_Process"
colnames(SWATH_results)[21] = "GO_Cellular_Component"
colnames(SWATH_results)[22] = "GO_Molecular_Function"
colnames(SWATH_results)[23] = "Tissue"
colnames(SWATH_results)[24] = "Subcellular_Location"
colnames(SWATH_results)[25] = "Signal_Peptide"

#Select significant p-values only
SWATH_results_p_filtered <- SWATH_results %>% 
  filter(P_Value <0.05)
```

```{r, warning=FALSE}
#Non filtered by specific proteins
#VOLCANO PLOTS
#make volcano plots from all data in log fold change
SWATH_results$diffexpressed <- "Not Sig"

#if log2Foldchange > 0.3 (2) and pvalue < 0.05, set as "UP" 
SWATH_results$diffexpressed[SWATH_results$Log_Fold_Change > 0.3 & 
                              SWATH_results$P_Value < 0.05] <- "Up"

#if log2Foldchange < -0.2 (0.59) and pvalue < 0.05, set as "DOWN"
SWATH_results$diffexpressed[SWATH_results$Log_Fold_Change < -0.2 & 
                              SWATH_results$P_Value < 0.05] <- "Down"

SWATH_results$delabel <- NA
SWATH_results$delabel[SWATH_results$diffexpressed != "Not Sig"] <- SWATH_results$Peak_Name[SWATH_results$diffexpressed != "Not Sig"]

#Plot
#Note: you will get an error message stating that values were removed. 
#This is due to large dataset but does not affect sig values. 
library(ggrepel)
volcano <- ggplot(data=SWATH_results, aes(x=Log_Fold_Change, y=-log10(P_Value), 
                               col=diffexpressed, label=delabel)) +
        geom_point() +
        # geom_text(size = 3) + 
        theme_minimal() +
        ggrepel::geom_text_repel(show.legend = FALSE,
                                 size = 3) +
        scale_color_manual(values=c("#008176","black", "#c1272d")) +
        geom_vline(xintercept=c(-0.2, 0.3), col="black") +
        geom_hline(yintercept=-log10(0.05), col="black") +
        labs(color = 'Differentially Expressed',
             x = "Log Fold Change",
             y = "-log10 p-value") +
        theme_classic()
        
volcano + ggtitle(label = "LC-MS/MS Analysis of Secretome",
                  subtitle = "BMP9 to Vehicle Control") 

ggsave("volcano.png", device = "png", 
       dpi = 600) 
```
```{r}
library(ggplot2)
library(ggrepel)
library(dplyr)

# Define proteins of interest
proteins_of_interest <- c("ISLR", "SOST", "IBP3", "IGF2", "CO4A2", "SYNC", "FBLN5", "CCN2", "CXCL5", "GROA", "PP14B")

# Initialize diffexpressed column
SWATH_results$diffexpressed <- "Not Sig"

# Set diffexpressed categories based on criteria
SWATH_results$diffexpressed[SWATH_results$Log_Fold_Change > 0.2 & 
                              SWATH_results$P_Value < 0.05] <- "Up"
SWATH_results$diffexpressed[SWATH_results$Log_Fold_Change < -0.2 & 
                              SWATH_results$P_Value < 0.05] <- "Down"

# Label only specific proteins of interest
SWATH_results$delabel <- NA
SWATH_results$delabel[SWATH_results$Peak_Name %in% proteins_of_interest] <- SWATH_results$Peak_Name[SWATH_results$Peak_Name %in% proteins_of_interest]

# Plot
volcano333 <- ggplot(data=SWATH_results, aes(x=Log_Fold_Change, y=-log10(P_Value), 
                               col=diffexpressed, label=delabel)) +
        geom_point() +
        ggrepel::geom_text_repel(show.legend = FALSE, size = 4) +
        scale_color_manual(values=c("Not Sig" = "black", "Up" = "red", "Down" = "blue")) +
        geom_vline(xintercept=c(-0.2, 0.2), col="black") +
        geom_hline(yintercept=-log10(0.05), col="black") +
        labs(color = 'Differentially Expressed',
             x = "Log Fold Change",
             y = "-log10 p-value") +
        theme_classic() +
        ggtitle(label = "LC-MS/MS Analysis of Secretome",
                subtitle = "BMP9 to Vehicle Control") +
        theme(
    axis.title.x = element_text(size = 14),  # X-axis label size
    axis.title.y = element_text(size = 14),  # Y-axis label size
    axis.text.x = element_text(size = 12),   # X-axis tick labels size
    axis.text.y = element_text(size = 12),   # Y-axis tick labels size
    legend.text = element_text(size = 12),   # Legend text size
    legend.title = element_text(size = 14)   # Legend title size
  )

volcano333

# Save the plot
ggsave("volcano333.png", plot = volcano333, device = "png", dpi = 900,  width = 7, height = 5)

```



```{r}
library(ggplot2)
library(ggrepel)
library(dplyr)

# Define proteins of interest
proteins_of_interest <- c("ISLR", "SOST", "IGFBP3")

# Filter the dataset to include only the proteins of interest
SWATH_results_filtered <- SWATH_results %>%
  filter(Peak_Name %in% proteins_of_interest)

# Initialize diffexpressed column
SWATH_results_filtered$diffexpressed <- "Not Sig"

# Set diffexpressed categories based on criteria
SWATH_results_filtered$diffexpressed[SWATH_results_filtered$Log_Fold_Change > 0.3 & 
                                      SWATH_results_filtered$P_Value < 0.05] <- "Up"
SWATH_results_filtered$diffexpressed[SWATH_results_filtered$Log_Fold_Change < -0.2 & 
                                      SWATH_results_filtered$P_Value < 0.05] <- "Down"

# Label significant proteins
SWATH_results_filtered$delabel <- NA
SWATH_results_filtered$delabel[SWATH_results_filtered$diffexpressed != "Not Sig"] <- SWATH_results_filtered$Peak_Name[SWATH_results_filtered$diffexpressed != "Not Sig"]

# Plot
volcano_filtered <- ggplot(data=SWATH_results_filtered, aes(x=Log_Fold_Change, y=-log10(P_Value), 
                                                           col=diffexpressed, label=delabel)) +
  geom_point() +
  ggrepel::geom_text_repel(show.legend = FALSE, size = 3) +
  scale_color_manual(values=c("Not Sig" = "black", "Up" = "#008176", "Down" = "#c1272d")) +
  geom_vline(xintercept=c(-0.2, 0.3), col="black") +
  geom_hline(yintercept=-log10(0.05), col="black") +
  labs(color = 'Differentially Expressed',
       x = "Log Fold Change",
       y = "-log10 p-value") +
  theme_classic() +
  ggtitle(label = "LC-MS/MS Analysis of Secretome",
          subtitle = "BMP9 to Vehicle Control")

volcano_filtered

# Save the plot
ggsave("volcano_filtered.png", plot = volcano_filtered, device = "png", dpi = 600)

```



```{r}
#VOLCANO PLOTS SPECIFIC PROTEINS of INTEREST
#make volcano plots from all data in log fold change
SWATH_results_2 <- SWATH_results

SWATH_results_specific <- SWATH_results_2 %>%
                                filter(str_detect(Peak_Name, "CCN2|SOST|IGF2|CCN2|IBP3|POSTN|CRIM1|FBLN5|ISLR|CD14|BGH3|IBP2|CXCL5|SPRC|FBLN2|SPON2|SMD3|IL6|GROA|SYNC|CO4A2|PP14B|FAM3C|MMP2"))

SWATH_results_specific$diffexpressed <- "Not Sig"
SWATH_results_2$diffexpressed <- "Not Sig"

SWATH_results_2 <- SWATH_results_2[!grepl("CCN2|SOST|IGF2|CCN2|IBP3|CRIM1|FBLN5|ISLR|CD14|BGH3|IBP2|CXCL5|FBLN2|SPON2|SMD3|IL6|GROA|SYNC|CO4A2|PP14B|FAM3C|MMP2", SWATH_results$Peak_Name),]

#if log2Foldchange > 0.6 and pvalue < 0.05, set as "UP" 
SWATH_results_specific$diffexpressed[SWATH_results_specific$Log_Fold_Change > 0.3 & 
                              SWATH_results_specific$P_Value < 0.05] <- "Up"

#if log2Foldchange < -0.6 and pvalue < 0.05, set as "DOWN"
SWATH_results_specific$diffexpressed[SWATH_results_specific$Log_Fold_Change < -0.2 & 
                              SWATH_results_specific$P_Value < 0.05] <- "Down"

#bind 
SWATH_results_specific <- rbind(SWATH_results_2, SWATH_results_specific)

SWATH_results_specific$delabel <- NA
SWATH_results_specific$delabel[SWATH_results_specific$diffexpressed != "Not Sig"] <- SWATH_results_specific$Peak_Name[SWATH_results_specific$diffexpressed != "Not Sig"]

#Plot
#Note: you will get an error message stating that values were removed. 
#This is due to large dataset but does not affect sig values. 
library(ggrepel)
volcano2 <- ggplot(data=SWATH_results_specific, aes(x=Log_Fold_Change, y=-log10(P_Value), 
                                                    col=diffexpressed, label=delabel)) +
        geom_point() + 
       # geom_text(size = 3) +
        theme_minimal() +
        ggrepel::geom_text_repel(show.legend = FALSE,
                                size = 3) +
        scale_color_manual(values=c("tan", "black", "#4dbbd5b2")) +
        geom_vline(xintercept=c(-0.2, 0.3), col="black") +
        geom_hline(yintercept=-log10(0.05), col="black") +
        labs(color = 'Differentially Expressed',
             x = "Log Fold Change",
             y = "-log10 p-value") +  
        theme_classic()

volcano2
        
volcano2 + theme(text = element_text(size = 15)) +theme(plot.title = element_text(family = "Calibri"))
ggsave("volcano2.png", device = "png", 
       dpi = 600) 
```

```{r}
library(ggplot2)
library(ggrepel)
library(dplyr)
library(stringr)

# Assuming SWATH_results_2 is already defined and contains your full dataset
SWATH_results_2 <- SWATH_results

# Filter specific proteins of interest
SWATH_results_specific <- SWATH_results_2 %>%
  filter(str_detect(Peak_Name, "CCN2|SOST|IGF2|IBP3|POSTN|CRIM1|FBLN5|ISLR|CD14|BGH3|IBP2|CXCL5|SPRC|FBLN2|SPON2|SMD3|IL6|GROA|SYNC|CO4A2|PP14B|FAM3C|MMP2"))

# Initialize diffexpressed column
SWATH_results_specific$diffexpressed <- "Not Sig"
SWATH_results_2$diffexpressed <- "Not Sig"

# Set diffexpressed categories based on criteria
SWATH_results_specific$diffexpressed[SWATH_results_specific$Log_Fold_Change > 0.3 & 
                                      SWATH_results_specific$P_Value < 0.05] <- "Up"

SWATH_results_specific$diffexpressed[SWATH_results_specific$Log_Fold_Change < -0.2 & 
                                      SWATH_results_specific$P_Value < 0.05] <- "Down"

# Exclude specific proteins from the full dataset
SWATH_results_2 <- SWATH_results_2[!grepl("CCN2|SOST|IGF2|IBP3|CRIM1|FBLN5|ISLR|CD14|BGH3|IBP2|CXCL5|FBLN2|SPON2|SMD3|IL6|GROA|SYNC|CO4A2|PP14B|FAM3C|MMP2", SWATH_results$Peak_Name),]

# Bind datasets
SWATH_results_specific <- rbind(SWATH_results_2, SWATH_results_specific)

# Label significant proteins
SWATH_results_specific$delabel <- NA
SWATH_results_specific$delabel[SWATH_results_specific$diffexpressed != "Not Sig"] <- SWATH_results_specific$Peak_Name[SWATH_results_specific$diffexpressed != "Not Sig"]

# Check unique values in diffexpressed
print(unique(SWATH_results_specific$diffexpressed))

# Plot
volcano2 <- ggplot(data=SWATH_results_specific, aes(x=Log_Fold_Change, y=-log10(P_Value), 
                                                    col=diffexpressed, label=delabel)) +
  geom_point() + 
  ggrepel::geom_text_repel(show.legend = FALSE, size = 3) +
  scale_color_manual(values=c("Not Sig" = "black", "Up" = "#4dbbd5b2", "Down" = "tan")) +
  geom_vline(xintercept=c(-0.2, 0.3), col="black") +
  geom_hline(yintercept=-log10(0.05), col="black") +
  labs(color = 'Differentially Expressed',
       x = "Log Fold Change",
       y = "-log10 p-value") +  
  theme_classic()

volcano2

```

```{r}
library(ggplot2)
library(ggrepel)
library(dplyr)
library(stringr)

# Filter specific proteins of interest
SWATH_results_specific <- SWATH_results_2 %>%
  filter(str_detect(Peak_Name, "CCN2|SOST|IGF2|IBP3|POSTN|CRIM1|FBLN5|ISLR|CD14|BGH3|IBP2|CXCL5|SPRC|FBLN2|SPON2|SMD3|IL6|GROA|SYNC|CO4A2|PP14B|FAM3C|MMP2"))

# Initialize and update diffexpressed column
SWATH_results_specific$diffexpressed <- "Not Sig"
SWATH_results_specific$diffexpressed[SWATH_results_specific$Log_Fold_Change > 0.3 & 
                                      SWATH_results_specific$P_Value < 0.05] <- "Up"
SWATH_results_specific$diffexpressed[SWATH_results_specific$Log_Fold_Change < -0.2 & 
                                      SWATH_results_specific$P_Value < 0.05] <- "Down"

# Verify column names to ensure 'Peak_Name' exists in the dataframe
print(colnames(SWATH_results_2))

# Check for NA values in the Peak_Name column
print(any(is.na(SWATH_results_2$Peak_Name)))

# Ensure correct usage of grepl and subsetting
# Use SWATH_results_2 and check the logic
SWATH_results_2 <- SWATH_results_2[!grepl("CCN2|SOST|IGF2|IBP3|CRIM1|FBLN5|ISLR|CD14|BGH3|IBP2|CXCL5|FBLN2|SPON2|SMD3|IL6|GROA|SYNC|CO4A2|PP14B|FAM3C|MMP2", SWATH_results_2$Peak_Name), ]

# Bind datasets
SWATH_results_specific <- rbind(SWATH_results_2, SWATH_results_specific)

# Label significant proteins
SWATH_results_specific$delabel <- NA
SWATH_results_specific$delabel[SWATH_results_specific$diffexpressed != "Not Sig"] <- SWATH_results_specific$Peak_Name[SWATH_results_specific$diffexpressed != "Not Sig"]

# Ensure diffexpressed is a factor with specific levels
SWATH_results_specific$diffexpressed <- factor(SWATH_results_specific$diffexpressed, 
                                               levels = c("Not Sig", "Up", "Down"))

# Check unique values in diffexpressed
print(unique(SWATH_results_specific$diffexpressed))

# Plot
volcano2 <- ggplot(data=SWATH_results_specific, aes(x=Log_Fold_Change, y=-log10(P_Value), 
                                                    col=diffexpressed, label=delabel)) +
  geom_point() + 
  ggrepel::geom_text_repel(show.legend = FALSE, size = 3) +
  scale_color_manual(values=c("Not Sig" = "black", "Up" = "#4dbbd5b2", "Down" = "tan")) +
  geom_vline(xintercept=c(-0.2, 0.3), col="black") +
  geom_hline(yintercept=-log10(0.05), col="black") +
  labs(color = 'Differentially Expressed',
       x = "Log Fold Change",
       y = "-log10 p-value") +  
  theme_classic()

volcano2

```


```{r}
# Analyze SWATH intensities for a specific protein BAC data
dataa <- read.csv("Intensities.csv")

dataa2 <- dataa %>% 
  pivot_longer(
    cols = starts_with("VWS"),
    names_to = "Sample",
    names_prefix = "VWS",
    values_to = "Intensity",
    values_drop_na = TRUE
  )

# IMPORTANT this needs to be generated according to the type of dataset
# (will be different for each one)
dataa2$Sample[dataa2$Sample == "100.BAC.HiPC.CM.B9.008"] <- "BMP9"
dataa2$Sample[dataa2$Sample == "100.BAC.HiPC.CM.B9.009"] <- "BMP9"
dataa2$Sample[dataa2$Sample == "100.BAC.HiPC.CM.B9.010"] <- "BMP9"
dataa2$Sample[dataa2$Sample == "100.BAC.HiPC.CM.Ctrl004"] <- "CTRL"
dataa2$Sample[dataa2$Sample == "100.BAC.HiPC.CM.Ctrl005"] <- "CTRL"
dataa2$Sample[dataa2$Sample == "100.BAC.HiPC.CM.Ctrl006"] <- "CTRL"


# dataa3 <- dataa2[dataa2$Peak.Name=="FINC", ]
dataa3 <- dataa2 %>% filter(str_detect(Peak.Name,"CCN2|SOST|IGF2|IBP3|POSTN|CRIM1|FBLN5|ISLR|CD14|
                                       BGH3|IBP2|CXCL5|SPRC|FBLN2|SPON2|IL6|GROA|SYNC|MMP2|
                                       "))

dataaa3 <- dataa2 %>% filter(str_detect(Peak.Name,"CCN2|SOST|IGF2|IBP3|POSTN|CRIM1|FBLN5|ISLR|CD14|
                                       BGH3|IBP2|SPRC|FBLN2|IL6|MMP2|
                                       "))
```

```{r}
# BOX PLOTS
BAC_CM_intensities <- ggplot(dataa3, aes(x=Peak.Name, y=Intensity, fill=Sample)) +
  geom_boxplot() +
  facet_wrap(~Peak.Name, scale = "free") +
  scale_fill_manual(values=c("#008176", "#c1272d")) +
  theme_light() +
  theme(strip.text.x = element_text(face = "italic"))  +
  xlab("")

BAC_CM_intensities 

ggsave("BAC_CM_intensities.png", device = "png", 
       dpi = 600) 

BAC_CM_intensities2 <- ggplot(dataaa3, aes(x=Peak.Name, y=Intensity, fill=Sample)) +
  geom_boxplot() +
  facet_wrap(~Peak.Name, scale = "free") +
  scale_fill_manual(values=c("#008176", "#c1272d")) +
  theme_light() +
  theme(strip.text.x = element_text(face = "italic")) +
  xlab("")

BAC_CM_intensities2

ggsave("BAC_CM_intensities2.png", device = "png", 
       dpi = 600) 
```


